/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosIdRouteImport } from './routes/eventos.$id'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as FinanceiroFluxoRouteImport } from './routes/financeiro.fluxo'
import { Route as FinanceiroPagarRouteImport } from './routes/financeiro.pagar'
import { Route as FinanceiroReceberRouteImport } from './routes/financeiro.receber'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos.index'
import { Route as OrcamentosIdRouteImport } from './routes/orcamentos.$id'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIdRoute = EventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroFluxoRoute = FinanceiroFluxoRouteImport.update({
  id: '/financeiro/fluxo',
  path: '/financeiro/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroPagarRoute = FinanceiroPagarRouteImport.update({
  id: '/financeiro/pagar',
  path: '/financeiro/pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroReceberRoute = FinanceiroReceberRouteImport.update({
  id: '/financeiro/receber',
  path: '/financeiro/receber',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIdRoute = OrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/orcamentos/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/eventos/$id': typeof EventosIdRoute
  '/financeiro/fluxo': typeof FinanceiroFluxoRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/eventos/$id': typeof EventosIdRoute
  '/financeiro/fluxo': typeof FinanceiroFluxoRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/orcamentos': typeof OrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estoque': typeof EstoqueRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/eventos/$id': typeof EventosIdRoute
  '/financeiro/fluxo': typeof FinanceiroFluxoRoute
  '/financeiro/pagar': typeof FinanceiroPagarRoute
  '/financeiro/receber': typeof FinanceiroReceberRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/estoque'
    | '/clientes/$id'
    | '/eventos/$id'
    | '/financeiro/fluxo'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/clientes/'
    | '/eventos/'
    | '/financeiro/'
    | '/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/estoque'
    | '/clientes/$id'
    | '/eventos/$id'
    | '/financeiro/fluxo'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/clientes'
    | '/eventos'
    | '/financeiro'
    | '/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/estoque'
    | '/clientes/$id'
    | '/eventos/$id'
    | '/financeiro/fluxo'
    | '/financeiro/pagar'
    | '/financeiro/receber'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/clientes/'
    | '/eventos/'
    | '/financeiro/'
    | '/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstoqueRoute: typeof EstoqueRoute
  ClientesIdRoute: typeof ClientesIdRoute
  EventosIdRoute: typeof EventosIdRoute
  FinanceiroFluxoRoute: typeof FinanceiroFluxoRoute
  FinanceiroPagarRoute: typeof FinanceiroPagarRoute
  FinanceiroReceberRoute: typeof FinanceiroReceberRoute
  OrcamentosIdRoute: typeof OrcamentosIdRoute
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$id': {
      id: '/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof EventosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/fluxo': {
      id: '/financeiro/fluxo'
      path: '/financeiro/fluxo'
      fullPath: '/financeiro/fluxo'
      preLoaderRoute: typeof FinanceiroFluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/pagar': {
      id: '/financeiro/pagar'
      path: '/financeiro/pagar'
      fullPath: '/financeiro/pagar'
      preLoaderRoute: typeof FinanceiroPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/receber': {
      id: '/financeiro/receber'
      path: '/financeiro/receber'
      fullPath: '/financeiro/receber'
      preLoaderRoute: typeof FinanceiroReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/$id': {
      id: '/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof OrcamentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstoqueRoute: EstoqueRoute,
  ClientesIdRoute: ClientesIdRoute,
  EventosIdRoute: EventosIdRoute,
  FinanceiroFluxoRoute: FinanceiroFluxoRoute,
  FinanceiroPagarRoute: FinanceiroPagarRoute,
  FinanceiroReceberRoute: FinanceiroReceberRoute,
  OrcamentosIdRoute: OrcamentosIdRoute,
  OrcamentosNovoRoute: OrcamentosNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
